#![allow(non_snake_case)]
use crate::CPU;

type InstructionFunc = fn(&CPU) -> ();
type AddessingMode = fn() -> ();

enum InstructionsNames {
	ADC,
	AND,
	ASL,
	BCC,
	BCS,
	BEQ,
	BIT,
	BMI,
	BNE,
	BPL,
	BRK,
	BVC,
	BVS,
	CLC,
	CLD,
	CLI,
	CLV,
	CMP,
	CPX,
	CPY,
	DEC,
	DEX,
	DEY,
	EOR,
	INC,
	INX,
	INY,
	JMP,
	JSR,
	LDA,
	LDX,
	LDY,
	LSR,
	NOP,
	ORA,
	PHA,
	PHP,
	PLA,
	PLP,
	ROL,
	ROR,
	RTI,
	RTS,
	SBC,
	SEC,
	SED,
	SEI,
	STA,
	STX,
	STY,
	TAX,
	TAY,
	TSX,
	TXA,
	TXS,
	TYA,
}

pub struct Instruction {
	name: InstructionsNames,
	function: InstructionFunc,
	mode: AddessingMode,
	cycles: u8,
}

impl Instruction {
	// All the 256 instructions present on the 6502 datasheet
	// ref: http://www.oxyron.de/html/opcodes02.html
	pub const INSTRUCTIONS: [Instruction; 256] = [
		Instruction {
			name: InstructionsNames::BRK,
			function: CPU::BRK,
			mode: CPU::IMP,
			cycles: 7,
		},
		Instruction {
			name: InstructionsNames::ORA,
			function: CPU::ORA,
			mode: CPU::IZX,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMP,
			cycles: 8,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMP,
			cycles: 3,
		},
		Instruction {
			name: InstructionsNames::ORA,
			function: CPU::ORA,
			mode: CPU::ZP0,
			cycles: 3,
		},
		Instruction {
			name: InstructionsNames::ASL,
			function: CPU::ASL,
			mode: CPU::ZP0,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMP,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::PHP,
			function: CPU::PHP,
			mode: CPU::IMP,
			cycles: 3,
		},
		Instruction {
			name: InstructionsNames::ORA,
			function: CPU::ORA,
			mode: CPU::IMM,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::ASL,
			function: CPU::ASL,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMM,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABS,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::ORA,
			function: CPU::ORA,
			mode: CPU::ABS,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::ASL,
			function: CPU::ASL,
			mode: CPU::ABS,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABS,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::BPL,
			function: CPU::BPL,
			mode: CPU::REL,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::ORA,
			function: CPU::ORA,
			mode: CPU::IZY,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IZY,
			cycles: 8,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ZPX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::ORA,
			function: CPU::ORA,
			mode: CPU::ZPX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::ASL,
			function: CPU::ASL,
			mode: CPU::ZPX,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ZPX,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::CLC,
			function: CPU::CLC,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::ORA,
			function: CPU::ORA,
			mode: CPU::ABY,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABY,
			cycles: 7,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::ORA,
			function: CPU::ORA,
			mode: CPU::ABX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::ASL,
			function: CPU::ASL,
			mode: CPU::ABX,
			cycles: 7,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABX,
			cycles: 7,
		},
		Instruction {
			name: InstructionsNames::JSR,
			function: CPU::JSR,
			mode: CPU::ABS,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::AND,
			function: CPU::AND,
			mode: CPU::IZX,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IZX,
			cycles: 8,
		},
		Instruction {
			name: InstructionsNames::BIT,
			function: CPU::BIT,
			mode: CPU::ZP0,
			cycles: 3,
		},
		Instruction {
			name: InstructionsNames::AND,
			function: CPU::AND,
			mode: CPU::ZP0,
			cycles: 3,
		},
		Instruction {
			name: InstructionsNames::ROL,
			function: CPU::ROL,
			mode: CPU::ZP0,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ZP0,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::PLP,
			function: CPU::PLP,
			mode: CPU::IMP,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::AND,
			function: CPU::AND,
			mode: CPU::IMM,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::ROL,
			function: CPU::ROL,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMM,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::BIT,
			function: CPU::BIT,
			mode: CPU::ABS,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::AND,
			function: CPU::AND,
			mode: CPU::ABS,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::ROL,
			function: CPU::ROL,
			mode: CPU::ABS,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABS,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::BMI,
			function: CPU::BMI,
			mode: CPU::REL,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::AND,
			function: CPU::AND,
			mode: CPU::IZY,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IZY,
			cycles: 8,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ZPX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::AND,
			function: CPU::AND,
			mode: CPU::ZPX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::ROL,
			function: CPU::ROL,
			mode: CPU::ZPX,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ZPX,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::SEC,
			function: CPU::SEC,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::AND,
			function: CPU::AND,
			mode: CPU::ABY,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABY,
			cycles: 7,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::AND,
			function: CPU::AND,
			mode: CPU::ABX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::ROL,
			function: CPU::ROL,
			mode: CPU::ABX,
			cycles: 7,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABX,
			cycles: 7,
		},
		Instruction {
			name: InstructionsNames::RTI,
			function: CPU::RTI,
			mode: CPU::IMP,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::EOR,
			function: CPU::EOR,
			mode: CPU::IZX,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IZY,
			cycles: 8,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ZP0,
			cycles: 3,
		},
		Instruction {
			name: InstructionsNames::EOR,
			function: CPU::EOR,
			mode: CPU::ZP0,
			cycles: 3,
		},
		Instruction {
			name: InstructionsNames::LSR,
			function: CPU::LSR,
			mode: CPU::ZP0,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ZP0,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::PHA,
			function: CPU::PHA,
			mode: CPU::IMP,
			cycles: 3,
		},
		Instruction {
			name: InstructionsNames::EOR,
			function: CPU::EOR,
			mode: CPU::IMM,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::LSR,
			function: CPU::LSR,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMM,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::JMP,
			function: CPU::JMP,
			mode: CPU::ABS,
			cycles: 3,
		},
		Instruction {
			name: InstructionsNames::EOR,
			function: CPU::EOR,
			mode: CPU::ABS,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::LSR,
			function: CPU::LSR,
			mode: CPU::ABS,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABS,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::BVC,
			function: CPU::BVC,
			mode: CPU::REL,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::EOR,
			function: CPU::EOR,
			mode: CPU::IZY,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IZY,
			cycles: 8,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ZPX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::EOR,
			function: CPU::EOR,
			mode: CPU::ZPX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::LSR,
			function: CPU::LSR,
			mode: CPU::ZPX,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ZPX,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::CLI,
			function: CPU::CLI,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::EOR,
			function: CPU::EOR,
			mode: CPU::ABY,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABY,
			cycles: 7,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::EOR,
			function: CPU::EOR,
			mode: CPU::ABX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::LSR,
			function: CPU::LSR,
			mode: CPU::ABX,
			cycles: 7,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABX,
			cycles: 7,
		},
		Instruction {
			name: InstructionsNames::RTS,
			function: CPU::RTS,
			mode: CPU::IMP,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::ADC,
			function: CPU::ADC,
			mode: CPU::IZX,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMP,
			cycles: 0,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IZX,
			cycles: 8,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ZP0,
			cycles: 3,
		},
		Instruction {
			name: InstructionsNames::ADC,
			function: CPU::ADC,
			mode: CPU::ZP0,
			cycles: 3,
		},
		Instruction {
			name: InstructionsNames::ROR,
			function: CPU::ROR,
			mode: CPU::ZP0,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ZP0,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::PLA,
			function: CPU::PLA,
			mode: CPU::IMP,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::ADC,
			function: CPU::ADC,
			mode: CPU::IMM,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::ROR,
			function: CPU::ROR,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMM,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::JMP,
			function: CPU::JMP,
			mode: CPU::IND,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::ADC,
			function: CPU::ADC,
			mode: CPU::ABS,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::ROR,
			function: CPU::ROR,
			mode: CPU::ABS,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABS,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::BVS,
			function: CPU::BVS,
			mode: CPU::REL,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::ADC,
			function: CPU::ADC,
			mode: CPU::IZY,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IZY,
			cycles: 8,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ZPX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::ADC,
			function: CPU::ADC,
			mode: CPU::ZPX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::ROR,
			function: CPU::ROR,
			mode: CPU::ZPX,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ZPX,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::SEI,
			function: CPU::SEI,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::ADC,
			function: CPU::ADC,
			mode: CPU::ABY,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABY,
			cycles: 7,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMP,
			cycles: 0,
		},
		Instruction {
			name: InstructionsNames::ADC,
			function: CPU::ADC,
			mode: CPU::ABX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::ROR,
			function: CPU::ROR,
			mode: CPU::ABX,
			cycles: 7,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABX,
			cycles: 7,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMM,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::STA,
			function: CPU::STA,
			mode: CPU::IZX,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMM,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IZX,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::STY,
			function: CPU::STY,
			mode: CPU::ZP0,
			cycles: 3,
		},
		Instruction {
			name: InstructionsNames::STA,
			function: CPU::STA,
			mode: CPU::ZP0,
			cycles: 3,
		},
		Instruction {
			name: InstructionsNames::STX,
			function: CPU::STX,
			mode: CPU::ZP0,
			cycles: 3,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ZP0,
			cycles: 3,
		},
		Instruction {
			name: InstructionsNames::DEY,
			function: CPU::DEY,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMM,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::TXA,
			function: CPU::TXA,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMM,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::STY,
			function: CPU::STY,
			mode: CPU::ABS,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::STA,
			function: CPU::STA,
			mode: CPU::ABS,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::STX,
			function: CPU::STX,
			mode: CPU::ABS,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABS,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::BCC,
			function: CPU::BCC,
			mode: CPU::IMP,
			cycles: 0,
		},
		Instruction {
			name: InstructionsNames::STA,
			function: CPU::STA,
			mode: CPU::IZY,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IZY,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::STY,
			function: CPU::STY,
			mode: CPU::ZPX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::STA,
			function: CPU::STA,
			mode: CPU::ZPX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::STY,
			function: CPU::STY,
			mode: CPU::ZPY,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ZPY,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::TYA,
			function: CPU::TYA,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::STA,
			function: CPU::STA,
			mode: CPU::IMP,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::TXS,
			function: CPU::TXS,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABY,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABX,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::STA,
			function: CPU::STA,
			mode: CPU::ABX,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABY,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABY,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::LDY,
			function: CPU::LDY,
			mode: CPU::IMM,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::LDA,
			function: CPU::LDA,
			mode: CPU::IZX,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::LDX,
			function: CPU::LDX,
			mode: CPU::IMM,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMP,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::LDY,
			function: CPU::LDY,
			mode: CPU::ZP0,
			cycles: 3,
		},
		Instruction {
			name: InstructionsNames::LDA,
			function: CPU::LDA,
			mode: CPU::ZP0,
			cycles: 3,
		},
		Instruction {
			name: InstructionsNames::LDX,
			function: CPU::LDX,
			mode: CPU::ZP0,
			cycles: 3,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ZP0,
			cycles: 3,
		},
		Instruction {
			name: InstructionsNames::TAY,
			function: CPU::TAY,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::LDA,
			function: CPU::LDA,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::TAX,
			function: CPU::TAX,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMM,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::LDY,
			function: CPU::LDY,
			mode: CPU::ABS,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::LDA,
			function: CPU::LDA,
			mode: CPU::ABS,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::LDX,
			function: CPU::LDX,
			mode: CPU::ABS,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABS,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::BCS,
			function: CPU::BCS,
			mode: CPU::REL,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::LDA,
			function: CPU::LDA,
			mode: CPU::IZY,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IZY,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::LDY,
			function: CPU::LDY,
			mode: CPU::ZPX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::LDA,
			function: CPU::LDA,
			mode: CPU::ZPX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::LDX,
			function: CPU::LDX,
			mode: CPU::ZPY,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ZPY,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::CLV,
			function: CPU::CLV,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::LDA,
			function: CPU::LDA,
			mode: CPU::ABY,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::TSX,
			function: CPU::TSX,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABY,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::LDY,
			function: CPU::LDY,
			mode: CPU::ABX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::LDA,
			function: CPU::LDA,
			mode: CPU::ABX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::LDX,
			function: CPU::LDX,
			mode: CPU::ABY,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABY,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::CPY,
			function: CPU::CPY,
			mode: CPU::IMM,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::CMP,
			function: CPU::CMP,
			mode: CPU::IZX,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMM,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IZX,
			cycles: 8,
		},
		Instruction {
			name: InstructionsNames::CPY,
			function: CPU::CPY,
			mode: CPU::ZP0,
			cycles: 3,
		},
		Instruction {
			name: InstructionsNames::CMP,
			function: CPU::CMP,
			mode: CPU::ZP0,
			cycles: 3,
		},
		Instruction {
			name: InstructionsNames::DEC,
			function: CPU::DEC,
			mode: CPU::ZP0,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ZP0,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::INY,
			function: CPU::INY,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::CMP,
			function: CPU::CMP,
			mode: CPU::IMM,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::DEX,
			function: CPU::DEX,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMM,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::CPY,
			function: CPU::CPY,
			mode: CPU::ABS,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::CMP,
			function: CPU::CMP,
			mode: CPU::ABS,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::DEC,
			function: CPU::DEC,
			mode: CPU::ABS,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABS,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::BNE,
			function: CPU::BNE,
			mode: CPU::REL,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::CMP,
			function: CPU::CMP,
			mode: CPU::IZY,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IZY,
			cycles: 8,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ZPX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::CMP,
			function: CPU::CMP,
			mode: CPU::ZPX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::DEC,
			function: CPU::DEC,
			mode: CPU::ZPX,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ZPX,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::CLD,
			function: CPU::CLD,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::CMP,
			function: CPU::CMP,
			mode: CPU::ABY,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABY,
			cycles: 7,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::CMP,
			function: CPU::CMP,
			mode: CPU::ABX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::DEC,
			function: CPU::DEC,
			mode: CPU::ABX,
			cycles: 7,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABX,
			cycles: 7,
		},
		Instruction {
			name: InstructionsNames::CPX,
			function: CPU::CPX,
			mode: CPU::IMM,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::SBC,
			function: CPU::SBC,
			mode: CPU::IZX,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMM,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IZX,
			cycles: 8,
		},
		Instruction {
			name: InstructionsNames::CPX,
			function: CPU::CPX,
			mode: CPU::ZP0,
			cycles: 3,
		},
		Instruction {
			name: InstructionsNames::SBC,
			function: CPU::SBC,
			mode: CPU::ZP0,
			cycles: 3,
		},
		Instruction {
			name: InstructionsNames::INC,
			function: CPU::INC,
			mode: CPU::ZP0,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ZP0,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::INX,
			function: CPU::INX,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::SBC,
			function: CPU::SBC,
			mode: CPU::IMM,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMM,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::CPX,
			function: CPU::CPX,
			mode: CPU::ABS,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::SBC,
			function: CPU::SBC,
			mode: CPU::ABS,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::INC,
			function: CPU::INC,
			mode: CPU::ABS,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABS,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::BEQ,
			function: CPU::BEQ,
			mode: CPU::REL,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::SBC,
			function: CPU::SBC,
			mode: CPU::IZY,
			cycles: 5,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IZY,
			cycles: 8,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IZY,
			cycles: 8,
		},
		Instruction {
			name: InstructionsNames::SBC,
			function: CPU::SBC,
			mode: CPU::ZPX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::INC,
			function: CPU::INC,
			mode: CPU::ZPX,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ZPX,
			cycles: 6,
		},
		Instruction {
			name: InstructionsNames::SED,
			function: CPU::SED,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::SBC,
			function: CPU::SBC,
			mode: CPU::ABY,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::IMP,
			cycles: 2,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABY,
			cycles: 7,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::SBC,
			function: CPU::SBC,
			mode: CPU::ABX,
			cycles: 4,
		},
		Instruction {
			name: InstructionsNames::INC,
			function: CPU::INC,
			mode: CPU::ABX,
			cycles: 7,
		},
		Instruction {
			name: InstructionsNames::NOP,
			function: CPU::NOP,
			mode: CPU::ABX,
			cycles: 7,
		},
	];
}
